name: 'GitHub Team Sync'
description: 'Synchronize GitHub Teams with the contents of a teams document'
author: 'rmacklin'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  repo-token:
    description: 'A GitHub access token secret - must have the admin:org scope'
  team-data-path:
    description: 'The path to the team data document'
    default: '.github/teams.yml'
  prefix-teams-with:
    description: 'A prefix to add to the name of each team when creating the associated GitHub Team'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
